ci: test [ci skip]

diff --git a/home/dot_local/bin/executable_chezmoi-feature b/home/dot_local/bin/executable_chezmoi-feature
--- a/home/dot_local/bin/executable_chezmoi-feature
+++ b/home/dot_local/bin/executable_chezmoi-feature
@@ -2,5 +2,96 @@
 
 set -eu
 
-chezmoi execute '{{ .features | toPrettyJson }}'
-# chezmoi execute '{{ .features | keys | join "\n" }}'
+usage() {
+  echo >&2 "Usage: chezmoi feature [list|enabled] [-h|--help]"
+  echo >&2 "  [-o|--output=text|json|yaml]"
+}
+
+get_format() {
+  format="${1:-}"
+  case "$output" in
+  text) ;;
+  json) format="toPrettyJson" ;;
+  yaml) format="toYaml" ;;
+  *)
+    echo >&2 "chezmoi package: invalid output format: $output"
+    usage
+    return 1
+    ;;
+  esac
+  echo "$format"
+}
+
+list_features() {
+  format="$(get_format 'keys | join "\n"')"
+  chezmoi execute "{{ .features | $format }}"
+}
+
+list_enabled_features() {
+  format="$(get_format 'join "\n"')"
+  # shellcheck disable=SC2016
+  tmpl='{{ $features := list }}{{ range $key, $value := .features }}{{ if $value }}{{ $features = append $features $key }}{{ end }}{{ end }}'
+  chezmoi execute "$tmpl{{ \$features | $format }}"
+}
+
+has_feature() {
+  key="$1"
+  # shellcheck disable=SC2016
+  value="$(chezmoi execute "{{ get .features \"$key\" }}")"
+  [ "$value" = true ]
+}
+
+action=
+output=text
+while [ $# -gt 0 ]; do
+  case "$1" in
+  list | enabled)
+    action="$1"
+    shift
+    # continue
+    ;;
+  -*=*)
+    key="${1%%=*}"
+    value="${1#*=}"
+    shift
+    set -- "$key" "$value" "$@"
+    ;;
+  -o | --output)
+    shift
+    output="$1"
+    shift
+    ;;
+  -o*)
+    output="${1#-o}"
+    shift
+    ;;
+  -h | --help)
+    usage
+    exit 0
+    ;;
+  *)
+    has_feature "$1"
+    shift
+    # echo >&2 "chezmoi package: invalid argument: $1"
+    # usage
+    # exit 1
+    ;;
+  esac
+done
+
+case "$action" in
+'')
+  # list_features | wc -l
+  ;;
+list)
+  list_features
+  ;;
+enabled)
+  list_enabled_features
+  ;;
+*)
+  echo >&2 "chezmoi feature: invalid action: $action"
+  usage
+  exit 1
+  ;;
+esac
