fix: packages

diff --git a/home/dot_local/bin/executable_chezmoi-render b/home/dot_local/bin/executable_chezmoi-render
--- a/home/dot_local/bin/executable_chezmoi-render
+++ b/home/dot_local/bin/executable_chezmoi-render
@@ -85,7 +85,8 @@ render() {
   # echo >&2 "render debug: ${cmd[*]} <${input#"$PWD"/}> -> ${out#"$PWD"/}"
   "${cmd[@]}" <"$input" >"$out" && exit_code=0 || exit_code=$?
   if [ "$exit_code" -ne 0 ]; then
-    echo >&2 "render failed: ${cmd[*]} <${input#"$PWD"/}> -> ${out#"$PWD"/}"
+    echo >&2 "render failed: exit code $exit_code"
+    # ${cmd[*]} <${input#"$PWD"/}> -> ${out#"$PWD"/}
   fi
   return "$exit_code"
 }
diff --git a/script/lint b/script/lint
--- a/script/lint
+++ b/script/lint
@@ -48,7 +48,7 @@ args=(
 set -- "${args[@]}" --files "${files[@]}"
 # echo >&2 "lint debug: prek run ${args[*]}"
 prek run "$@" && exit_code=0 || exit_code=$?
-if [ $exit_code -ne 0 ]; then
-  echo >&2 "lint failed: prek run ${args[*]}"
+if [ "$exit_code" -ne 0 ]; then
+  echo >&2 "lint failed: exit code $exit_code"
 fi
-exit $exit_code
+exit "$exit_code"
