a

diff --git a/bin/args b/bin/args
--- a/bin/args
+++ b/bin/args
@@ -14,59 +14,129 @@ err() {
 }
 
 parse_args() {
-  local args=(${PARSE_ARGS[@]})
+  local cmd=(${PARSE_ARGS[@]:0:1})
+  local args=(${PARSE_ARGS[@]:1})
   local parsed=()
-  local arg
-  # for a in "$@"
   while [[ $# -ne 0 ]]
   do
     case "$1" in
       -|'') err "invalid argument -" ;;
       --) break ;;
-      -*) [[ "$next" -eq 1 ]] && err "invalid ${type:-argument}: $arg requires a value, found $1"
+      -*) [[ "$next" -eq 1 ]] && err "illegal option $1"
         local pre="-${a%%-*}"
         local p
         for p in "${args[@]}"
         do
           local type next=0
-          local req="${p##*:}"
+          local req="${p#*:}"
+          [[ "$p" == "$req" ]] && unset req
           if [[ "$req" == *- ]]
           then type="stdin"; req="${req%-*}"; next=1
           fi
           if [[ "$req" == *+* ]]
           then type="${req#*+}"; req="${req%+*}"; next=1
           fi
-          p="${p%:*}"
+          p="${p%%:*}"
           local short="${p%|*}"
           local name="${p#*|}"
-          local ptn="(-$short|--$name)" #($pre)*([a-zA-Z]+)?(=)"
+          local ptn="(-$short|--$name)([a-zA-Z]+)?" #($pre)*([a-zA-Z]+)?(=)"
           if [[ $1 =~ $ptn ]]
-          then arg="$1"
+          then
+            # >&2 echo "[[ $1 =~ $ptn ]]"
+            # >&2 echo "$short,$name req $req ($next)"
+            # local prefix="${BASH_REMATCH[1]}"
+            local arg="${BASH_REMATCH[1]}"
+            local extra="${BASH_REMATCH[2]}"
+            # >&2 printf "MATCH %s\n" "${BASH_REMATCH[@]}"
+            if [[ "$arg" == "--"* ]] && [[ -n "$extra" ]]
+            then err "$arg: illegal option"
+            elif [[ "$arg" == "-"* ]] && [[ -n "$extra" ]]
+            then set -- "$arg" "-$extra" "${@:2}"
+              # >&2 echo "NEXT:$next => $@"
+              # if [[ "$next" -eq 1 ]]
+              # then echo >&2 "THEN" "-$arg" "${@:2:1}" "-$extra" "${@:3}"
+              #   set -- "-$arg" "${@:2:1}" "-$extra" "${@:3}"
+              # else echo >&2 "ELSE" "-$arg" "-$extra" "${@:2}"
+              #   set -- "-$arg" "-$extra" "${@:2}"
+              # fi
+            elif [[ -n "$extra" ]]
+            then err "invalid option $arg"
+            fi
             local varname="${name//-/_}"
-            # parsed+=("$p")
-            # TODO while $2 if next 1
-              # >&2 log "$a NEXT $next"
+            local res=
             if [[ "$next" -eq 1 ]]
             then
-                # >&2 log "???? $# / $1 / $2 ($type) "
-                # if [[ $# -gt 1 ]] && [[ "$type" == "stdin" ]] && [[ -f "$2" ]]
-                # then log "$varname=@$2"
-              # elif [[ "$type" == "stdin" ]] && [[ -z "$2" ]]
-              # then log "$varname=@-" # [[ -t 0 ]]
-              if [[ $# -gt 1 ]] && [[ -n "$2" ]] && [[ "$2" != -* ]]
-              then log "$varname=$2"
-              # elif [[ "$type" != "stdin" ]]
-              else err "Unexpected value ($name,$1) $2 [$#]"
+              if [[ "$type" == "stdin" ]]
+              then
+                if [[ $# -gt 1 ]] && [[ "$2" != -* ]]
+                then [[ -f "$2" ]] && res="$varname=@$2" || res="$varname=$2"; shift
+                else res="$varname=@-"; next=0 # [[ -t 0 ]]
+                fi
+              elif [[ $# -gt 1 ]] && [[ -n "$2" ]] && [[ "$2" != -* ]]
+              then res="$varname=$2"; shift
+              elif  [[ -n "$2" ]]
+              then err "$1: $name requires a ${type:-value}, found: $2"
+              else err "$1: $name requires a ${type:-value}"
               fi
-              shift # key
-            else log "$varname=1"
+            else res="$varname=1"
             fi
             shift # key or value
+            parsed+=("$res" "${req:-}")
+            printf "%s\n" "$res"
             break
           fi
+          # >&2 echo "did not break /$p/ $@"
         done
+        if [[ -z "$arg" ]]
+        then err "illegal option $1"
+        fi
         ;;
       *) err "$1? [$@] $#"
+        ;;
+    esac
+  done
+
+# declare -A cant_go=([create]=remove,delete,shred); declare -A cant_tbl=();add_cant() { [[ ${cant_tbl[$2,len]} ]] ||
+# 2016-12-03 14:58         resh | cant_tbl[$2,len]=0;cant_tbl[$2,${cant_tbl[$2,len]}]=$1;((cant_tbl[$2,len] ++));};add_cant_row(){ local param=$1 with
+# 2016-12-03 14:58         resh | w;IFS=, read -ra with;for w in "${with[@]}"; do add_cant "$w" "$param"; done;};for p in "${!cant_go[@]}";do
+# 2016-12-03 14:58         resh | add_cant_row "$p" <<<"${cant_go[$p]}";done;declare -p cant_tbl
+# 2016-12-03 14:58        shbot | resh: declare -A cant_tbl=([create,len]="3" [create,0]="remove" [create,1]="delete" [create,2]="shred" )
+
+# declare -A cant_t=([create,len]="1" [create,0]="remove")
+# in_cant_t(){
+#   local len=${cant_t[$1,len]} i;[[ $len ]] || {false;return;}
+#   for ((i=0;i<len;i++)); do [[ ${cant_t[$prm,$i]} == "$vs" ]]&&{ true;return;};done;false;
+# }
+# vldt(){
+#   local a=$1;shift;local b
+#   for b;do if in_cant_t "$a" "$b";then echo "$a cnt go wth $b";fi;done;
+# }
+# set -- create delete
+# for ((i=1;i<=$#;i++))
+# do vldt "${!i}" "${@: i+1}"
+# done
+
+  # local i requires
+  # for ((i=0; i<${#parsed[@]}; i+=2))
+  # do
+  #   arg="${parsed[i]}"
+  #   echo >&2 ">>>>>>>>>>>>>>>>>> $arg ${parsed[i+1]}"
+  #   while IFS=$',' read -r req
+  #   do
+  #     if [[ -n "$req" ]]
+  #     then
+  #       case "$req" in
+  #         \&*) >&2 log "$arg AND $r" ;;
+  #         \|*) >&2 log "$arg OR $r" ;;
+  #         \!*) >&2 log "$arg NOT $r" ;;
+  #         *) >&2 log "$arg /$req/"; req= ;;
+  #       esac
+  #     fi
+  #   done <<< ${parsed[i+1]}
+  # done
+}
+
+___parse_args() {
         # local val=
         # case "$type" in
         #   '') val="$a"; shift ;;
@@ -76,8 +146,6 @@ parse_args() {
         #   stdin) [[ -n "$a" ]] && [[ -t 0 ]] && err "invalid input $name: $a"; val="$a"; shift ;;
         #   *) err "invalid type: $type" ;;
         # esac
-        ;;
-    esac
     # if [[ -n "$arg" ]] && [[ -z "$val" ]] && [[ "$next" -eq 1 ]]
     # then continue
     # elif [[ -n "$arg" ]] && [[ -n "$val" ]] && [[ "$next" -eq 1 ]]
@@ -94,15 +162,8 @@ parse_args() {
     # fi
 
     # if [[ -n "$req" ]]
-    # then log "$a requires $req"
+    # then >&2 log "$arg  1:$1 2:$2 requires /$req/ in ${parsed[@]}"
     # fi
-  done
-
-  # if [[ "$next" -eq 1 ]]
-  # then err "missing ${type:-argument} for ${long:-$a}" #$long"
-  # fi
-
-  return $?
 
   local _args="$@"
   local args=(${PARSE_ARGS[@]})
