printf

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -16,43 +16,50 @@ set -o pipefail
 # # Recursive globbing (bash 4)
 # shopt -s globstar
 
-# Platform
-UNAME=$(uname -s | tr '[:upper:]' '[:lower:]') #Darwin|Linux
-
-# Paths
-cd $(dirname "${BASH_SOURCE[0]}")/..
-DOT_ROOT=$(pwd -P)
-DOT_TARGET=$HOME
-DOT_SCRIPT="$DOT_ROOT/script"
-DOT_RC="$DOT_ROOT/.dotrc"
-
-# Load libraries
-source $DOT_SCRIPT/lib/import.sh
-
-import "log"
-import "prompt"
-import "config"
-
 function dot() {
+    # Platform
+    UNAME=$(uname -s | tr '[:upper:]' '[:lower:]') # darwin|linux
 
-  	if config "$DOT_RC"; then
-  		log_success "Hello, $DOT_AUTHOR_NAME" "$DOT_RC"
-  	else
-  		log_error "Could not generate config" "$DOT_RC"
-  		die "$DOT_RC"
-  	fi
+    # Paths
+    export DOT_ROOT=$HOME/.dotfiles
+    [[ -d "$DOT_ROOT" ]] || die "$DOT_ROOT: No such file or directory"
+    # cd $(dirname "${BASH_SOURCE[0]}")/..
+    # cd $(dirname "$(readlink "${BASH_SOURCE[0]}")")/..
+    # DOT_ROOT=$(pwd -P)
+
+    DOT_TARGET=$HOME
+    DOT_SCRIPT="$DOT_ROOT/script"
+    DOT_RC="$DOT_ROOT/.dotrc"
+
+    # Load libraries
+    source $DOT_SCRIPT/lib/import.sh
+
+    import "log"
+    import "prompt"
+    import "config"
+    import "usage"
+
+    # Parse command options
+    parse_arguments "$@"
+
+	if config "$DOT_RC"; then
+		log_success "Hello, $DOT_AUTHOR_NAME" "$DOT_RC"
+	else
+		log_error "Could not generate config" "$DOT_RC"
+		die "$DOT_RC"
+	fi
 
     # Configuration (DOT_CONFIG_*)
     # [[ -n "${DOT_CONFIG_DEBUG-}" ]] && DEBUG="$DOT_CONFIG_DEBUG"
     # [[ -n "${DOT_CONFIG_DRY_RUN-}" ]] && DRY_RUN="$DOT_CONFIG_DRY_RUN"
     # [[ -n "${DOT_CONFIG_FORCE-}" ]] && FORCE="$DOT_CONFIG_FORCE"
     # [[ -n "${DOT_CONFIG_TIMESTAMPS-}" ]] && TIMESTAMPS="$DOT_CONFIG_TIMESTAMPS"
-    DEBUG="${DOT_CONFIG_DEBUG-${DEBUG-false}}"
-    DRY_RUN="${DOT_CONFIG_DRY_RUN-${DRY_RYN-false}}"
-    FORCE="${DOT_CONFIG_FORCE-${FORCE-false}}"
-    TIMESTAMPS="${DOT_CONFIG_TIMESTAMPS-${TIMESTAMPS-false}}"
+    DEBUG="${DEBUG-${DOT_CONFIG_DEBUG-false}}"
+    DRY_RUN="${DRY_RUN-${DOT_CONFIG_DRY_RYN-false}}"
+    FORCE="${FORCE-${DOT_CONFIG_FORCE-false}}"
+    TIMESTAMPS="${TIMESTAMPS-${DOT_CONFIG_TIMESTAMPS-false}}"
 
-  	log_debug "Debug mode" "$BASH_VERSION"
+	log_debug "Debug mode" "$BASH_VERSION"
 
     if confirm "Homebrew install" "" Y; then
         # Install dependencies
@@ -70,6 +77,55 @@ function dot() {
     fi
 
     log_success "Done" "STATUS $?"
+}
+
+parse_arguments() {
+	while [[ $# -gt 0 ]]; do
+		local key=$1
+		local val=${2-}
+
+        # echo "Parsing $1 (#$#)"
+
+		case $key in
+			-d|--debug)
+				DEBUG=true
+				shift
+				;;
+			--dry-run)
+				DRY_RUN=true
+				shift
+				;;
+			# -t|--target)
+			# 	shift
+            #
+			# 	# Loop until next '-', cannot handle ' -' without quotes
+			# 	# while [[ $# -gt 0 ]] && [[ $1 != -* ]]; do
+			# 	# 	DOT_TARGET+=" $1"
+			# 	# 	shift
+			# 	# done
+            #
+			# 	# Check value until the delimiter '-' is found or end of args
+			# 	if [[ $# -gt 0 ]] && [[ ! -z "$val" ]] && [[ $val != -* ]]; then
+			# 		shift
+			# 	else
+            #         # Ask for the missing value
+            #         local prompt="Please specify a target path (default: $HOME): "
+            #         read -e -r -p "$prompt" val # -i "$HOME"
+            #         # Use default
+            #         [[ -z "$val" ]] && break
+			# 	fi
+			# 	# Check destination path
+			# 	[[ -d "$val" ]] || usage 1 "Not a directory: $key $val"
+			# 	DOT_TARGET="$val"
+			# 	;;
+			-h|--help)
+				usage
+				;;
+			*)
+				usage 1 "Unknown option: $key"
+				;;
+		esac
+	done
 }
 
 die() {
