term

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -54,7 +54,7 @@ boot() {
   TIMESTAMPS="${TIMESTAMPS-${DOT_CONFIG_TIMESTAMPS-false}}"
 
   # Platform specific
-  UNAME=$(uname -s | to_lower) # darwin|linux
+  UNAME=$(uname -s) # Darwin|Linux
 
   # Git config credential helper
   if [[ "$UNAME" = "darwin" ]]; then
@@ -66,7 +66,7 @@ boot() {
   # Greeting
   log_info "Hello, $DOT_USER_NICK" "$DOT_USER_NAME <$DOT_USER_EMAIL>"
   log_debug "Debug mode enabled" "$BASH_VERSION"
-  log_debug "Dry run > > > > > >" "$DRY_RUN"
+  log_debug "DRY RUN" "$DRY_RUN"
 
   # Start script
   dot "$DOT_CMD"
@@ -76,14 +76,14 @@ dot() {
   local cmd=$1
 
   case $cmd in
+    install)
+      dot_install
+      ;;
     git)
       dot_git
       ;;
     list)
       dot_list
-      ;;
-    install)
-      dot_install
       ;;
     link)
       dot_bootstrap
@@ -92,6 +92,7 @@ dot() {
       dot_defaults
       ;;
     '') # Default to all
+      confirm "Update git submodules" "" Y && dot_git
       confirm "**Homebrew install" "" Y && dot_install
       confirm "**Symlink files to $DOT_TARGET" "" Y && dot_bootstrap
       confirm "**Setup $UNAME specific defaults" "" Y && dot_defaults
@@ -103,22 +104,11 @@ dot() {
   esac
 
   if [[ $? -eq 0 ]]; then
-    log_success "Done" "whit status $?"
+    log_success "Done" "= $?"
   else
-    log_error "Error" "with status $?"
-
+    log_error "Error" "= $?"
     return $?
   fi
-}
-
-dot_git() {
-  import "lib/git"
-  git_submodule
-}
-
-dot_list() {
-  import "bootstrap/symlinks"
-  bootstrap_symlinks list
 }
 
 dot_install() {
@@ -128,7 +118,12 @@ dot_install() {
   # Install dependencies
   install_brew && \
     install_cask || \
-    log_warn "Install aborted"
+    log_warn "Install aborted" "= $?"
+}
+
+dot_git() {
+  import "lib/git"
+  git_submodule
 }
 
 dot_bootstrap() {
@@ -138,7 +133,12 @@ dot_bootstrap() {
   # Bootstrap dotfiles
   bootstrap_templates && \
     bootstrap_symlinks build || \
-    log_warn "Bootstrap aborted"
+    log_warn "Bootstrap aborted" "= $?"
+}
+
+dot_list() {
+  import "bootstrap/symlinks"
+  bootstrap_symlinks list
 }
 
 dot_defaults() {
@@ -146,7 +146,7 @@ dot_defaults() {
 
   # Set platform defaults
   platform_defaults || \
-    log_warn "Defaults aborted"
+    log_warn "Defaults aborted" "= $?"
 }
 
 parse_arguments() {
@@ -155,7 +155,7 @@ parse_arguments() {
     local val=${2-}
     # echo "Parsing $1 (#$#)"
     case $key in
-      list|install|uninstall|link|unlink|defaults)
+      git|list|install|uninstall|link|unlink|defaults)
         # Check if a command is already defined
         [[ -n "${DOT_CMD-}" ]] && usage 1 "Too many arguments: $key"
         # Register main action
