n

diff --git a/bin/parse b/bin/parse
--- a/bin/parse
+++ b/bin/parse
@@ -20,7 +20,7 @@ parse() {
     then local p="${1%_*}"
       spec+=("${1##*_}")
       if [[ "$1" == "$spec" ]]
-      then >&2 printf "%s\n" "parse: missing arg spec /*_$/ -- $1"; exit 1
+      then >&2 printf "%s\n" "parse: missing arg spec /*_$/ -- $1"; return 1
       fi
       case $p in
         duration,*) p="${p/duration,/number,}@get_seconds" ;;
@@ -28,7 +28,7 @@ parse() {
       patterns+=("${p}")
       shift
     elif [[ $1 =~ $types,* ]] # type,(p|pattern)@function"
-    then >&2 printf "%s\n" "parse: invalid arg spec -- $1"; exit 1
+    then >&2 printf "%s\n" "parse: invalid arg spec -- $1"; return 1
     else break
     fi
   done
@@ -58,7 +58,7 @@ parse() {
       # >&2 printf "%s\n" "Match spec ${spec[i]}?"
       fi
 
-      p="-($short|[a-zA-Z-]+|-)?( |=)"
+      p="-+($short|[a-zA-Z-]+|-)?( |=)"
       if [[ $a =~ $p ]]
       then
         local extra="${BASH_REMATCH[1]}"
@@ -77,7 +77,7 @@ parse() {
       # >&2 printf "%s =~ /%s/ ?\n" "${a[@]}" "${spec[i]%+}"
     done
     if [[ $a =~ -([a-zA-Z][a-zA-Z]+)?(\ |=)  ]]
-    then >&2 printf "%s\n" "parse: unknown option -- ${BASH_REMATCH[1]}"; exit 1
+    then >&2 printf "%s\n" "parse: unknown option -- ${BASH_REMATCH[1]}"; return 1
     # TODO handle unkown arguments
     else break
     fi
@@ -116,7 +116,7 @@ parse() {
           bool)
             if [[ -z "$val" ]]
             then val=true; shift
-            else >&2 printf "%s\n" "parse: switch '$pre$key' does not require a value"; exit 1
+            else >&2 printf "%s\n" "parse: switch '$pre$key' does not require a value"; return 1
             fi
             ;;
           string)
@@ -124,7 +124,7 @@ parse() {
             then shift
             elif [[ $# -gt 1 ]]
             then val="$2"; shift; shift
-            else >&2 printf "%s\n" "parse: switch '$pre$key' requires a string"; exit 1
+            else >&2 printf "%s\n" "parse: switch '$pre$key' requires a string"; return 1
             fi
             ;;
           number)
@@ -133,8 +133,8 @@ parse() {
             elif [[ $# -gt 1 ]]
             then val="$2"; shift; shift;
             elif [[ ! $val =~ ^-?[0-9]+$ ]]
-            then >&2 printf "%s\n" "parse: switch '$pre$key' requires a number"; exit 1
-            else >&2 printf "%s\n" "parse: switch '$pre$key' requires a value"; exit 1
+            then >&2 printf "%s\n" "parse: switch '$pre$key' requires a number"; return 1
+            else >&2 printf "%s\n" "parse: switch '$pre$key' requires a value"; return 1
             fi
             ;;
           *) >&2 echo "NO TYPE $1"; break ;;
@@ -154,7 +154,7 @@ parse() {
         # Extra arguments
         # then printf ":%s\n" "$@"
         if [[ "$match" -eq 0 ]]
-        then >&2 printf "%s\n" "parse: unknown option -- $@"; exit 1
+        then >&2 printf "%s\n" "parse: unknown option -- $@"; return 1
         fi
       fi
     done
