args

diff --git a/bin/parse b/bin/parse
--- a/bin/parse
+++ b/bin/parse
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# Parse arguments
+# Usage: PARSE_ARGS="type,v|var[,R|required]" parse "$@"
 
 set -e
 set -o pipefail
@@ -15,8 +17,10 @@ parse() {
   then >&2 printf "%s\n" "parse: missing arguments"
     return 1
   fi
+  local a len="${#args[@]}"
   while [[ $# -ne 0 ]]
-  do local a max="${#args[@]}"
+  do local a max="$len"
+    >&2 echo MAX $max
     for a in "${args[@]}"
     do
       local type="${a%%,*}"
@@ -26,7 +30,7 @@ parse() {
       p="${p%%,*}"
       local long="${p##*|}"
       local short="${p%%|*}"
-      local name="${long/-/_}"
+      local name="${long//-/_}"
       local spec="${a##*,}"
       # local func="${a##*@}"
       # if [[ "$a" != "$func" ]]
@@ -39,7 +43,7 @@ parse() {
       # local pattern="^(-${p%|*}|--${p#*|})([a-zA-Z-]*)( |=)?(.*)$"
       local pattern="^(-${short}|--${long})([a-zA-Z]*)?( |=)?(.*)$"
       if [[ $1 =~ $pattern ]]
-      then # >&2 printf "MATCH '%s'\n" "${BASH_REMATCH[@]}"
+      then >&2 printf "MATCH '%s'\n" "${BASH_REMATCH[@]}"
         # >&2 printf "%s\t=~\t%s\n" "'$1'" "$pattern"
         # [[ "${1:0:1}" == "${1:1:1}" ]] && prefix="--" || prefix="-"
         # local prefix="${BASH_REMATCH[1]}"
@@ -52,38 +56,45 @@ parse() {
           # If short key, look for extra arguments
           if [[ "$1" != "--"* ]] && [[ -n "$next" ]]
           then
-            if [[ "$spec" == *+ ]]
-            then # Re-order arguments
-              set -- "${@:1:1}" "-$next$sep$val" "${@:2}"
-              set -- "${@:2:1}" "$key" "${@:3}"
-              continue
-            else # Split short arguments
+            if [[ "$type" == "bool" ]] && [[ -n "$val" ]]
+            then
+              set -- "${@:1:1}" "-$next" "${@:2}"
+              set -- "${@:2:1}" "$key${sep}$val" "${@:3}"
+              continue # Reset loop
+            else
+              # >&2 echo "${@:1:1}" "$key" "${@:2}"
+              # >&2 echo "${@:2:1}" "-$next$sep$val" "${@:3}"
               set -- "${@:1:1}" "$key" "${@:2}"
-              set -- "${@:2:1}" "-$next$sep$val" "${@:3}"
+              set -- "${@:2:1}" "-$next${sep}$val" "${@:3}"
             fi
+          # elif [[ "$type" != "bool" ]] && [[ -n "$next" ]]
+          # then >&2 printf "%s\n" "parse: invalid argument ${name} ${key} requires a value ${next}" ##*|
           fi
-          local s _s _spec="${spec%+}"
+          >&2 echo "=> $@"
           if [[ -n "$spec" ]]
           then
+            local s _s
             while IFS=$'&' read -ra _s
             do
               for s in "${_s[@]}"
               do local check
                 if [[ "$s" == !* ]]
-                then check="absent"; s="${s#!}" #; pattern="($s!)"
-                else check="present" #; pattern="($s)"
+                then check=0 s="${s#!}" #; pattern="($s!)"
+                else check=1 #; pattern="($s)"
                 fi
-                pattern="-([a-zA-Z]*)+($s)"
-
-                # >&2 echo "[[ ${_args[@]} =~ $pattern ]] /// $p"
-
-                if [[ ! ${_args[@]} =~ $pattern ]] && [[ "$check" == "present" ]]
-                then # s="${BASH_REMATCH[1]:--$s}"
-                  >&2 printf "%s\n" "parse: invalid argument $key (${s} should be $check)"
-                  return 1
-                elif [[ ${_args[@]} =~ $pattern ]] && [[ "$check" == "absent" ]]
-                then s="${BASH_REMATCH[2]:--$s}"
-                  >&2 printf "%s\n" "parse: invalid argument $key (-${s##*|} should be $check)"
+                pattern="-([a-zA-Z]*)+($s)(a-zA-Z]*)*"
+                # >&2 echo -e "$key => $check /$s/" # ${_args[@]}
+                if [[ ! ${_args[@]} =~ $pattern ]] && [[ "$check" -gt 0 ]]
+                then msg="requires" # s="${BASH_REMATCH[1]:--$s}"
+                elif [[ ${_args[@]} =~ $pattern ]] && [[ "$check" -eq 0 ]]
+                then msg="cannot be used with" # s="${BASH_REMATCH[2]:--$s}"
+                fi
+                # s="${s/${short}|-${long}/}"
+                # [[ "${s##*]}" != "${s%|*}" ]] && s="${s%|*} or ${s##*|}"
+                s="${s//[a-zA-Z]|-/--}"
+                s="[ ${s//|/ ] | [ } ]"
+                if [[ -n "$msg" ]]
+                then >&2 printf "%s\n" "parse: invalid argument ${name} ${key} ${msg}: ${s}" ##*|
                   return 1
                 fi
                 # if [[ ${_args[@]} =~ $pattern ]] #&& [[ "$check" == "present" ]]
@@ -101,7 +112,7 @@ parse() {
                 #   return 1
                 # fi
               done
-            done <<< "$_spec"
+            done <<< "$spec"
             # if [[ "$spec" = *"&"* ]]
             # then echo >&2 "S2 ${spec##*&}"
             # fi
@@ -141,6 +152,10 @@ parse() {
           # Check value
           case "$type" in
             bool)
+              if [[ -n "$val" ]]
+              then >&2 printf "%s\n" "parse: invalid $key does not require a value (got '$val')"
+                return 1
+              fi
               val="$true"
               # if [[ -n "$val" ]] # && [[ "$val" != "$true" ]]
               # then >&2 printf "%s\n" "parse: switch '$long' does not require a value -- $val"
@@ -150,28 +165,22 @@ parse() {
               ;;
             string)
               if [[ -z "$val" ]]
-              then >&2 printf "%s\n" "parse: invalid $type $key (got '$val')"
+              then >&2 printf "%s\n" "parse: invalid $type $key: $val"
                 return 1
               fi
               ;;
             number)
               if [[ -z "$val" ]] || [[ ! $val =~ ^-?[0-9]+$ ]]
-              then >&2 printf "%s\n" "parse: invalid $type $key (got '$val')"
+              then >&2 printf "%s\n" "parse: invalid $type $key: $val"
                 return 1
               fi
               ;;
+            *) >&2 printf "%s\n" "parse: invalid type: $type"
+              return 1
+              ;;
           esac
 
-          # Check value specification
-          if [[ "$spec" == *+ ]] && [[ -z "$val" ]]
-          then >&2 printf "%s\n" "parse: invalid $key requires a $type"
-            return 1
-          elif [[ "$spec" != *+ ]] && [[ -n "$val" ]] && [[ "$type" != bool ]]
-          then >&2 printf "%s\n" "parse: invalid $key does not require a value (got '$val', expecting $type)"
-            return 1
-          fi
-
-          # Output
+          # Output # TODO check dupes?
           printf "%s=%s\n" "${name}" "${val}"
 
           shift
@@ -181,7 +190,7 @@ parse() {
         fi
       else # >&2 echo "MAX: $max"
         max=$((max - 1))
-        if [[ "$max" -eq 0 ]]
+        if [[ "$max" -le 0 ]]
         then a="${_args/${1#-}*/${1#-}}"
           >&2 printf "%s\n" "parse: invalid argument -- ${a##* }"
           return 1
