parse

diff --git a/bin/parse b/bin/parse
--- a/bin/parse
+++ b/bin/parse
@@ -4,30 +4,45 @@ set -e
 set -o pipefail
 shopt -s extglob
 
+# get_seconds
+source "${BASH_DIR:-$HOME/.bash.d}/functions/time.bash"
+
 parse() {
-  local types="bool|string"
+  local types="bool|string|number|duration"
   local arg_pattern="($types),([a-zA-Z|\|\-]+)"
   local patterns=() args=()
 
   while [[ $# -ne 0 ]]
   do
     if [[ $1 =~ $arg_pattern ]]
-    then patterns+=("$1"); shift
-    elif [[ $1 =~ $types,* ]]
+    then local t="$1"
+      case $t in
+        duration,*) t="${t/duration,/number,}@get_seconds" ;;
+      esac
+      patterns+=("$t")
+      shift
+    elif [[ $1 =~ $types,* ]] # type,(p|pattern)@function"
     then >&2 printf "%s\n" "parse: invalid arg spec -- $1"; exit 1
     else break
     fi
-  done
+  done # >&2 printf "%s\n" "${patterns[@]}"
 
-  local len=$#
-  while [[ $# -ne 0 ]] && [[ "$len" -gt 0 ]]
-  do
-    local p= t= name=
+  local plen="${#patterns[@]}"
+  local t p func name match="$plen"
+  local pre key next sep val
+  while [[ $# -ne 0 ]] && [[ "$match" -ne 0 ]]
+  do match="$plen"
+    unset t p func name
     for p in "${patterns[@]}"
-    do local pre= key= next= sep= val=
-      t="${p%,*}"; p="${p#*,}" name="${p##*|}"
-      p="(-|--)($p)+([a-zA-Z]+|-)?( |=)?(.*)"
-      # echo "[[ $1 =~ $p ]]"
+    do # >&2 echo "Arguments: '$@'"
+      unset pre key next sep val
+      if [[ $p == *@* ]]
+      then func="${p##*@}"; [[ -n "$func" ]] && p="${p%@*}"
+      fi
+      t="${p%%,*}" # Type
+      p="${p#*,}" # Pattern
+      name="${p##*|}" # Long name
+      p="(-|--)($p)+([a-zA-Z]+|-)?( |=)?(.*)" # >&2 echo "[[ $1 =~ $p ]]"
       if [[ $1 =~ $p ]]
       then
         # if [[ "${BASH_REMATCH[1]:0:1}" == "${BASH_REMATCH[1]:1:1}" ]]
@@ -40,12 +55,12 @@ parse() {
         next="${BASH_REMATCH[3]:-}"
         sep="${BASH_REMATCH[4]:-}"
         val="${BASH_REMATCH[5]:-}"
-        # echo "PRE: $pre" "KEY: $key" "NEXT: $next" "SEP: '$sep'"
+        # >&2 echo "PRE: $pre" "KEY: $key" "NEXT: $next" "SEP: '$sep'"
         case $t in
           bool)
             if [[ -z "$val" ]]
             then val=true; shift
-            else >&2 printf "%s\n" "error: switch '$pre$key' does not require a value, got '$val'"; exit 1
+            else >&2 printf "%s\n" "error: switch '$pre$key' does not require a value'"; exit 1
             fi
             ;;
           string)
@@ -53,6 +68,16 @@ parse() {
             then shift
             elif [[ $# -gt 1 ]]
             then val="$2"; shift; shift
+            else >&2 printf "%s\n" "parse: switch '$pre$key' requires a string"; exit 1
+            fi
+            ;;
+          number)
+            if [[ -n "$val" ]]
+            then shift
+            elif [[ $# -gt 1 ]]
+            then val="$2"; shift; shift;
+            elif [[ ! $val =~ ^-?[0-9]+$ ]]
+            then >&2 printf "%s\n" "parse: switch '$pre$key' requires a number"; exit 1
             else >&2 printf "%s\n" "parse: switch '$pre$key' requires a value"; exit 1
             fi
             ;;
@@ -61,18 +86,21 @@ parse() {
         if [[ -n "$next" ]]
         then set -- "$pre$next" "${@:1:1}" "${@:2}"
         fi
-        # echo "PRE: $pre" "KEY: $key" "NEXT: $next" "SEP: '$sep', VAL: $val"
-        # args+=("$name" "$val")
+        if [[ -n "$func" ]] # && hash "${func%% *}" 2>/dev/null
+        then val="$($func "$val")"
+        # else >&2 echo "$val ${func%% *}"
+        fi
+        # >&2 echo "PRE: $pre" "KEY: $key" "NEXT: $next" "SEP: '$sep', VAL: $val"
         printf "%s:%s\n" "$name" "$val"
-        len=$#
-      else # Extra arguments
-        len=$((len -1)) # ((len--))
-        if [[ "$len" -eq 0 ]]
+      else
+        # >&2 echo "miss /$p/ $@"
+        match=$((match - 1))
+        # Extra arguments
+        if [[ "$match" -eq 0 ]]
         then printf ":%s\n" "$@"
         fi
       fi
     done
-    # >&2 echo "last: $last / name: $name / next: $next"
     # if [[ -z "$next" ]] && [[ -n "$name" ]] || [[ "$last" == "$name" ]]
     # then >&2 echo "NO MATCH $1"; shift
     # fi
diff --git a/bin/pb b/bin/pb
--- a/bin/pb
+++ b/bin/pb
@@ -2,11 +2,28 @@
 # http://ptpb.pw/#shell-functions
 # https://github.com/HalosGhost/pbpst
 
-# get_seconds
-source "${BASH_DIR:-$HOME/.bash.d}/functions/time.bash"
-
 PB_CURL_OPTS=
 PB_PROVIDER="https://ptpb.pw" #-CRUShdpfuvx
+# read -d '' PB_ARGS <<"EOF"
+# EOF
+PB_ARGS=("bool,h|help" \
+"bool,d|debug" \
+"string,P|provider" \
+"bool,C|create" \
+"bool,U|update" \
+"bool,R|remove" \
+"bool,S|shorten" \
+"string,G|get" \
+"bool,lf|list-formats" \
+"bool,ll|list-lexers" \
+"bool,ls|list-styles" \
+"bool,r|render" \
+"bool,t|term" \
+"string,f|file" \
+"bool,p|private" \
+"string,u|uuid" \
+"string,v|vanity" \
+"duration,x|sunset")
 
 set -e
 set -o pipefail
@@ -108,29 +125,9 @@ pb() {
       # declare "${k}=${v}"
     elif [[ -z "$k" ]] && [[ -n "$v" ]]
     then args+=("$v")
-    else >&2 printf "%s\n" "Missing key or value: ${k}:${v}"
+    else >&2 printf "%s\n" "Missing key or value: ${k}:${v}"; return 1
     fi
-  done < <(parse \
-    "bool,h|help" \
-    "bool,d|debug" \
-    "string,P|provider" \
-    "bool,C|create" \
-    "bool,U|update" \
-    "bool,R|remove" \
-    "bool,S|shorten" \
-    "string,G|get" \
-    "bool,lf|list-formats" \
-    "bool,ll|list-lexers" \
-    "bool,ls|list-styles" \
-    "bool,r|render" \
-    "bool,t|term" \
-    "string,f|file" \
-    "bool,p|private" \
-    "string,u|uuid" \
-    "string,v|vanity" \
-    "string,x|sunset" \
-    "$@") || usage
-  # echo $?
+  done < <(parse ${PB_ARGS[@]} "$@") || usage
 
   # if [[ -n "$debug" ]]
   # then
@@ -177,7 +174,7 @@ pb() {
   [[ -n "$provider" ]] && url="$provider"
   [[ -n "$render" ]] && url+="/r"
   [[ -n "$term" ]] && url+="/t"
-  [[ -n "$sunset" ]] && sunset="$(get_seconds "$sunset")"
+  # [[ -n "$sunset" ]] && sunset="$(get_seconds "$sunset")"
 
   if [[ "$get" -gt 1 ]]
   then usage "invalid action -ll -ls -lf"
