rd

diff --git a/bin/reverse-diff b/bin/reverse-diff
--- a/bin/reverse-diff
+++ b/bin/reverse-diff
@@ -2,17 +2,18 @@
 
 # Compare 2 files and output common lines
 
-err() {
-  >&2 printf "$0: %s\n" "$@"
-  exit 1
+# File or link
+isfile() {
+  [[ -f "$1" ]] && [[ -L "$1" ]]
 }
+
 main() {
-  if [[ $# -ne 2 ]]
-  then error
-  elif [[ -z "$1" ]] || [[ -z "$2" ]]
-  then error
+  if [[ $# -ne 2 ]] || [[ -z "$1" ]] || [[ -z "$2" ]]
+  then >&2 printf "%s\n" "$0: missing argument"
+  elif ! isfile "$1" || ! isfile "$2"
+  then >&2 printf "%s\n" "$0: not found"
+  else comm -1 -2 <(sort "$1") <(sort "$2")
   fi
-  comm -1 -2 <(sort "$1") <(sort "$2")
 }
 
 [[ "$0" == "$BASH_SOURCE" ]] && main "$@"
