usage+

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -16,71 +16,14 @@ export lib=$DOTFILES_DIR/lib
 
 # Get command
 args=("$@")
+debug=
+mute=
+force_default=
+force_all=
+reset_colors=
+verbose=
 
 set -e
-
-# Print command line usage
-echo_usage () {
-	$lib/usage
-	exit 0
-}
-
-echo_debug () {
-	if [ "$debug" = true ]; then
-		info "Symbolic dry run" "Changes are not applied while debugging" true
-	fi
-}
-
-copy () {
-	local src=$1
-
-	((indent_level++))
-	if [ -f "$src" -o -d "$src" ] && \
-		. $lib/copy $src $TARGET_DIR > /dev/null; then
-		success "$src" "Copied to ~/$src"
-	else
-		fail "$src" "Failed to be copied"
-	fi
-	((indent_level--))
-}
-
-remove () {
-	local src=$1
-	# Find target
-	local dst=$TARGET_DIR/${src#$DOTFILES_DIR/}
-
-	((indent_level++))
-	if [ -d "$dst" ]; then
-		info "${dst#$HOME/}" "Ignored (directory)" true
-	elif [ -f "$dst" -o -L "$dst" ] && rm $dst 2> /dev/null; then
-		success "${dst#$HOME/}" "Removed"
-	else
-		fail "${dst#$HOME/}" "Cannot be removed"
-	fi
-	((indent_level--))
-}
-
-check_file () {
-	local file=$1
-
-	if [ -f $file ]; then
-		return 1
-	else
-		return 0
-	fi
-}
-
-source_file () {
-	local file=$1
-
-	if [ -f $file ] && source "$file"; then
-		#success "Operation successfull !"
-		return 1
-	else
-		#fail "Command failed !"
-		return 0
-	fi
-}
 
 do_setup () {
 	# TODO Configuration file
@@ -100,12 +43,27 @@ do_setup () {
 	#git pull origin master
 
 	# Import functions
+	source $lib/utils
 	source $lib/print
 	source $lib/ask
 	source $lib/dir
+	source $lib/file
 	source $lib/link
 	source $lib/git
 	source $lib/brew
+}
+
+# Print command line usage
+echo_usage () {
+	$lib/usage
+	exit 0
+}
+
+echo_debug () {
+	if [ "$debug" = true ]; then
+		info "Debug is enabled." " " true
+		#info "Symbolic dry run" "Changes are not applied while debugging" true
+	fi
 }
 
 do_gitconfig () {
@@ -241,45 +199,9 @@ uninstall () {
 	end_message="Bootstrap uninstalled things."
 }
 
-# Parse arguments and unset recognized ones
-parse_flags () {
-	local args=("$@")
-
-	for (( i = ${#args[@]} - 1; i >= 0; i-- )); do
-		case ${args[i]} in
-			-d|--debug)
-				debug=true
-				unset args[i] ;;
-			# -?|--default)
-			# 	force_default=true
-			# 	unset args[i] ;;
-			# -f|--force)
-			# 	force=true
-			# 	unset args[i] ;;
-			-m|--mute)
-				mute=true
-				unset args[i] ;;
-			-s|--sandbox)
-				sandbox
-				unset args[i] ;;
-			-h|--help)
-				echo_usage
-				unset args[i] ;;
-			-*) echo "Unknown option: ${args[i]}"
-				echo_usage
-				unset args[i] ;;
-		esac
-	done
-
-	# Print echo_usage if > 1 argument left
-	[ ${#args[@]} -gt 1 ] && echo_usage
-
-	echo ${args[@]}
-}
-
 # Execute command
 bootstrap () {
-	cmd=$(parse_flags $@)
+	local cmd=$1
 
 	case $cmd in
 		'')          install ;;
@@ -288,19 +210,62 @@ bootstrap () {
 		'link')      do_link ;;
 		'copy')      do_copy ;;
 		'defaults')  do_defaults ;;
-		'bundle')    exec "set-up" ;;
+		'setup')     source_file $DOTFILES_DIR/setup ;;
 		*)           echo_usage ;;
 	esac
 }
 
-do_setup
-bootstrap ${args[@]}
+# Init
+if do_setup; then
 
-echo ''
-indent_level=0
+	# -?|--default)
+	# 	force_default=true
+	# 	unset args[i] ;;
+	# -f|--force)
+	# 	force_all=true
+	# 	unset args[i] ;;
+	# Parse arguments and unset recognized ones
+	for (( i = ${#args[@]} - 1; i >= 0; i-- )); do
+		case ${args[i]} in
+			-d|--debug)
+				debug=true
+				unset args[i] ;;
+			-h|--help)
+				echo_usage
+				unset args[i] ;;
+			-s|--sandbox)
+				echo sandbox
+				unset args[i] ;;
+			-u|--ugly)
+				reset_colors=true
+				unset args[i] ;;
+			-v|--verbose)
+				verbose=true
+				unset args[i] ;;
+			-*) echo "Unknown option: ${args[i]}"
+				echo_usage
+				unset args[i] ;;
+		esac
+	done
 
-[ -n "$end_message" ] || end_message="Things were bootstrapped !"
-success "$end_message" " "
+	export debug
 
-# source ~/.bash_profile || \
-# 	fail "~/.bash_profile"
+	# Print echo_usage if > 1 argument left
+	[ ${#args[@]} -gt 1 ] && echo_usage
+
+	# Launch
+	########
+
+	bootstrap ${args[@]}
+
+	echo ''
+	indent_level=0
+
+	# End
+	[ -n "$end_message" ] || end_message="Things were bootstrapped !"
+	success "$end_message" " "
+
+	# Can't get this to work
+	# source ~/.bash_profile || fail "~/.bash_profile"
+
+fi
