fix: carapace

diff --git a/home/.chezmoitemplates/init.sh.tmpl b/home/.chezmoitemplates/init.sh.tmpl
--- a/home/.chezmoitemplates/init.sh.tmpl
+++ b/home/.chezmoitemplates/init.sh.tmpl
@@ -74,7 +74,7 @@ bench() {
     fi
     # NOTE: zsh time does not work with other builtins like source
     # https://unix.stackexchange.com/a/478220/223694
-    time
+    {time} 2>&1 | head -n1
     "$@"
     TIMEFMT="$ORIGINAL_TIMEFMT"
     unset ORIGINAL_TIMEFMT
@@ -233,6 +233,19 @@ fi
 
 # Source plugins after updating PATH and activating mise
 source_plugins sh
+
+# https://carapace-sh.github.io/carapace-bin/setup.html#bash
+if command -v carapace >/dev/null; then
+  export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
+  if [ "$shell" = zsh ]; then
+    autoload -U +X compinit && compinit # Fixes "zsh: command not found: compdef"
+    zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
+  fi
+  # BENCHFMT="carapace" bench source <(carapace _carapace)
+  BENCHFMT="carapace" bench source <(carapace _carapace | sed -e 's/ && +X//')
+else
+  echo >&2 "Command 'carapace' not found"
+fi
 
 if command -v direnv >/dev/null; then
   BENCHFMT="direnv" bench eval "$(direnv hook "$shell")"
diff --git a/home/dot_config/sheldon/plugins.toml.tmpl b/home/dot_config/sheldon/plugins.toml.tmpl
--- a/home/dot_config/sheldon/plugins.toml.tmpl
+++ b/home/dot_config/sheldon/plugins.toml.tmpl
@@ -71,6 +71,25 @@ fi
 source_plugins sh
 """
 
+{{- if .features.carapace }}
+
+# https://carapace-sh.github.io/carapace-bin/setup.html#bash
+[plugins.carapace]
+inline = """
+if command -v carapace >/dev/null; then
+  export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
+  if [ "$shell" = zsh ]; then
+    autoload -U +X compinit && compinit # Fixes "zsh: command not found: compdef"
+    zstyle ':completion:*' format $'\\e[2;37mCompleting %d\\e[m'
+  fi
+  # BENCHFMT="carapace" bench source <(carapace _carapace)
+  BENCHFMT="carapace" bench source <(carapace _carapace | sed -e 's/ && +X//')
+else
+  echo >&2 "Command 'carapace' not found"
+fi
+"""
+{{- end }}
+
 {{- if .features.direnv }}
 
 [plugins.direnv]
@@ -108,6 +127,10 @@ fi
 # github = "chriskempson/base16-shell"
 
 {{- if eq $shell "zsh" }}
+
+[plugins.zsh-autosuggestions]
+github = "zsh-users/zsh-autosuggestions"
+use = ["{{ `{{ name }}` }}.zsh"]
 
 [plugins.zsh-syntax-highlighting]
 github = "zsh-users/zsh-syntax-highlighting"
