iii

diff --git a/roles/irc/files/connect b/roles/irc/files/connect
--- a/roles/irc/files/connect
+++ b/roles/irc/files/connect
@@ -3,49 +3,50 @@
 : "${ircdir:=$HOME/irc}"
 : "${nick:=$USER}"
 
-# server info functions
-freenode() {
-	server='irc.freenode.net'
-	channels="#foo #bar"
-}
+# # Server info functions
+# freenode() {
+#   server='irc.freenode.net'
+#   channels="#foo #bar"
+# }
 
-oftc() {
-	server='irc.oftc.net'
-	channels="#xyz #abc"
-}
+# oftc() {
+#   server='irc.oftc.net'
+#   channels="#xyz #abc"
+# }
 
-# these match the functions above
-networks="freenode oftc"
+# # These match the functions above
+# networks="freenode oftc"
 
-# some privacy please, thanks
+# Some privacy please, thanks
 chmod 700 "$ircdir"
 chmod 600 "$ircdir"/*/ident &>/dev/null
 
 for network in $networks; do
-	unset server channels port
-	"$network" # set the appropriate vars
+  unset server channels port
+  "$network" # Set the appropriate vars
 
-	while true; do
-		# cleanup
-		rm -f "$ircdir/$server/in"
+  while true; do
+    # Cleanup
+    rm -f "$ircdir/$server/in"
 
-		# connect to netwrok -- password is set through the env var synonym to the network name
-		iim -i "$ircdir" -n "$nick" -k "$network" -s "$server" -p "${port:-6667}" &
-		pid="$!"
+    # Connect to network -- password is set through the env var synonym to the network name
+    # iim -i "$ircdir" -n "$nick" -k "$network" -s "$server" -p "${port:-6667}" &
+    ii -i "$ircdir" -n "$nick" -k "$network" -s "$server" -p "${port:-6667}" &
+    pid="$!"
 
-		# wait for the connection
-		while ! test -p "$ircdir/$server/in"; do sleep .3; done
+    # Wait for the connection
+    while ! test -p "$ircdir/$server/in"; do sleep .3; done
 
-		# auth to services
-		if [ -e "$ircdir/$server/ident" ]
-		then printf "/j nickserv identify %s\n" "$(cat "$ircdir/$server/ident")" > "$ircdir/$server/in"
-		fi && rm -f "$ircdir/$server/nickserv/out" # clean that up - ident passwd is in there
+    # Auth to services
+    if [ -e "$ircdir/$server/ident" ]
+    then printf "/j nickserv identify %s\n" "$(cat "$ircdir/$server/ident")" > "$ircdir/$server/in"
+    fi && rm -f "$ircdir/$server/nickserv/out" # Clean that up - ident passwd is in there
 
-		# join channels
-		printf "/j %s\n" $channels > "$ircdir/$server/in"
+    # Join channels
+    printf "/j %s\n" $channels > "$ircdir/$server/in"
 
-		# if connection is lost reconnect
-		wait "$pid"
-	done &
+    # If connection is lost reconnect
+    wait "$pid"
+  done &
 done
 
