fix: packages [ci skip]

diff --git a/home/.chezmoiscripts/run_onchange_after_01-install-tools.sh.tmpl b/home/.chezmoiscripts/run_onchange_after_01-install-tools.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_after_01-install-tools.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_after_01-install-tools.sh.tmpl
@@ -1,11 +1,10 @@
-{{- if get .features "mise" -}}
 #!/bin/sh
 
 set -eu
 
 . "$CHEZMOI_WORKING_TREE/home/.chezmoitemplates/helpers.sh"
 
-{{- includeTemplate "dot_config/sh/plugins/mise.sh.tmpl" . }}
+{{ includeTemplate "dot_config/sh/plugins/mise.sh.tmpl" . | trim }}
 
 {{- $args := list "--yes" }}
 {{- if .chezmoi.config.verbose }}
@@ -13,57 +12,59 @@ set -eu
 {{- end }}
 {{- $miseArgs := $args | quoteList | join " " }}
 
+if [ "${DRY_RUN:-}" = true ]; then
+  set -- "$@" --dry-run
+fi
+
 {{- if .upgrade }}
 
-if ! cmd mise self-update {{ $miseArgs }}; then
-  echo >&2 "mise self-update failed with exit code $?"
+if ! run mise self-update "$@" {{ $miseArgs }}; then echo >&2 "mise self-update failed with exit code $?"
 fi
 {{- end }}
 
 # TODO: check gpg-agent is running
 
-# cmd mise trust
+# run mise trust "$@"
 
 # config.toml tools hash: {{ get (includeTemplate "dot_config/mise/config.toml.tmpl" . | fromToml) "tools" | toJson | sha256sum }}
-log "Installing tools"
+echo >&2 "Installing tools"
 
 # mise_args="--yes"
 # if [ "${CHEZMOI_VERBOSE:-}" = 1 ]; then
 #   mise_args="$mise_args --verbose"
 # fi
 
-cmd timeout 5m mise install {{ $miseArgs }}
+run timeout 5m mise install "$@" {{ $miseArgs }}
 
-log "Installed tools"
+echo >&2 "Installed tools"
 
-# cmd mise ls
+# run mise ls "$@"
 
 {{- $tools := list }}
 
-{{- if get .packages "go" }}
+{{- if get .packages.mise "go" }}
 # default-go-packages: {{ includeTemplate "dot_config/mise/default-go-packages.tmpl" . | sha256sum }}
 {{- $tools = append $tools "go" }}
 {{- end }}
 
-{{- if get .packages "node" }}
+{{- if get .packages.mise "node" }}
 # default-npm-packages: {{ includeTemplate "dot_config/mise/default-npm-packages.tmpl" . | sha256sum }}
 {{- $tools = append $tools "node" }}
 {{- end }}
 
-{{- if get .packages "python" }}
+{{- if get .packages.mise "python" }}
 # default-python-packages: {{ includeTemplate "dot_config/mise/default-python-packages.tmpl" . | sha256sum }}
 {{- $tools = append $tools "python" }}
 {{- end }}
 
-{{- if get .packages "ruby" }}
+{{- if get .packages.mise "ruby" }}
 # default-gems: {{ includeTemplate "dot_config/mise/default-gems.tmpl" . | sha256sum }}
 {{- $tools = append $tools "ruby" }}
 {{- end }}
 
 {{- if not (empty $tools) }}
 
-cmd mise use --global {{ $miseArgs }} {{ $tools | sortAlpha | join " " }}
+run mise use --global "$@" {{ $miseArgs }} {{ $tools | sortAlpha | join " " }}
 {{- end }}
 
-# cmd mise prune # --tools
-{{- end -}}
+# run mise prune "$@" # --tools
diff --git a/home/.chezmoiscripts/run_onchange_before_01-install-packages.sh.tmpl b/home/.chezmoiscripts/run_onchange_before_01-install-packages.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_before_01-install-packages.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_before_01-install-packages.sh.tmpl
@@ -16,10 +16,10 @@ packages="{{ $packageList | join " " }}"
 
 echo >&2 "Installing {{ .packageManager }} packages: $packages"
 
-{{- $before := includeTemplate "packages-script.tmpl" (mergeOverwrite . (dict
+{{- $before := includeTemplate "pluck.tmpl" (dict
   "key" "before_script"
-  "packages" $systemPackages
-)) | trim }}
+  "values" $systemPackages
+) | trim }}
 {{- if $before }}
 
 # Before script:
@@ -82,6 +82,12 @@ cmd sudo dnf install --assumeyes --quiet $packages
 if [ ! -d "$HOME/storage/shared" ]; then
   cmd termux-setup-storage
 fi
+
+# if [ -z "${TERMUX_APP_PACKAGE_MANAGER:-}" ]; then
+#   cmd termux-setup-package-manager
+#   TERMUX_APP_PACKAGE_MANAGER=apt
+# fi
+
 # TERM=xterm temux-change-repo # apt edit-sources
 
 # cat /data/data/com.termux/files/usr/etc/apt/sources.list
@@ -95,31 +101,27 @@ cmd pkg upgrade --quiet --yes
 {{- end }}
 
 cmd pkg install --quiet --yes $packages # >/dev/null
+{{- else if eq .os "windows" }}
+{{- if .upgrade }}
 
-# if [ -z "${TERMUX_APP_PACKAGE_MANAGER:-}" ]; then
-#   cmd termux-setup-package-manager
-#   TERMUX_APP_PACKAGE_MANAGER=apt
-# fi
-# if [ "$TERMUX_APP_PACKAGE_MANAGER" = apt ]; then
-#   # shellcheck disable=SC2086
-#   cmd apt-get install --quiet --yes $packages # >/dev/null
-# elif [ "$TERMUX_APP_PACKAGE_MANAGER" = pacman ]; then
-#   # shellcheck disable=SC2086
-#   cmd pacman --sync --needed --noconfirm --quiet $packages
-# else
-#   echo >&2 "Error: unknown package manager"
-#   exit 1
-# fi
+winget upgrade --all --disable-interactivity --silent
+{{- end }}
+
+# NOTE: winget.json is updated after apply
+# Winget packages hash: {{ includeTemplate "dot_config/winget/winget.json.tmpl" . | sha256sum }}
+winget import --import-file="$HOME/.config/winget/winget.json" --disable-interactivity
+{{- if not .upgrade }} --no-upgrade{{ end }}
+# --accept-package-agreements --accept-source-agreements
 {{- else }}
 
-echo >&2 "Package manager not found: {{ .osID }}"
+echo >&2 "Invalid OS: {{ .osID }}"
 exit 1
 {{- end }}
 
-{{- $after := includeTemplate "packages-script.tmpl" (mergeOverwrite . (dict
+{{- $after := includeTemplate "pluck.tmpl" (dict
   "key" "after_script"
-  "packages" $systemPackages
-)) | trim }}
+  "values" $systemPackages
+) | trim }}
 {{- if $after }}
 
 # After script:
diff --git a/home/dot_local/bin/executable_chezmoi-package b/home/dot_local/bin/executable_chezmoi-package
--- a/home/dot_local/bin/executable_chezmoi-package
+++ b/home/dot_local/bin/executable_chezmoi-package
@@ -5,9 +5,9 @@ set -eu
 uname="$(uname -s)"
 
 usage() {
-  echo >&2 "Usage: chezmoi package [list*|diff] [-h|--help]"
-  echo >&2 "  [-o|--output=text*|json|yaml]"
-  echo >&2 "  [-t|--type=all|apk|apt|aur|brew|cask|dnf|go|mas|node|pacman|python|ruby|rust|vscode]"
+  echo >&2 "Usage: chezmoi package [list|diff] [-h|--help]"
+  echo >&2 "  [all|apk|apt|aur|brew|cask|dnf|go|mas|node|pacman|python|ruby|rust|vscode]"
+  echo >&2 "  [-o|--output=text|json|yaml]"
 }
 
 action=list
@@ -18,7 +18,7 @@ while [ $# -gt 0 ]; do
   list | diff)
     action="$1"
     shift
-    continue
+    # continue
     ;;
   -*=*)
     key="${1%%=*}"
@@ -35,23 +35,27 @@ while [ $# -gt 0 ]; do
     output="${1#-o}"
     shift
     ;;
-  -t | --type)
-    shift
-    type="$1"
-    shift
-    ;;
-  -t*)
-    type="${1#-t}"
-    shift
-    ;;
+  # -t | --type)
+  #   shift
+  #   type="$1"
+  #   shift
+  #   ;;
+  # -t*)
+  #   type="${1#-t}"
+  #   shift
+  #   ;;
   -h | --help)
     usage
     exit 0
     ;;
   *)
-    echo >&2 "chezmoi package: invalid argument: $1"
-    usage
-    exit 1
+    if [ -n "$type" ]; then
+      echo >&2 "chezmoi package: invalid argument: $1"
+      usage
+      exit 1
+    fi
+    type="$1"
+    shift
     ;;
   esac
 done
@@ -65,9 +69,18 @@ list_packages() {
   case "$output" in
   text)
     # format='keys | sortAlpha | join "\n" | append "\n"'
-    chezmoi execute "{{ range .packages.$key | keys | sortAlpha }}{{ printf \"%s\n\" . }}{{ end }}"
-    # '{{ includeTemplate "packages-script.tmpl" (mergeOverwrite . (dict "key" "before_script" "packages" .packages.'"$key"')) | trim }}'
-    # '{{ includeTemplate "packages-script.tmpl" (mergeOverwrite . (dict "key" "after_script" "packages" .packages.'"$key"')) | trim }}'
+    template=.
+    case "$key" in
+    # Hide brew tap prefix
+    brew | cask) template='. | replaceAllRegex "[\\w@-]+/" ""' ;;
+    esac
+    chezmoi execute <<EOF
+{{ range .packages.$key | keys | sortAlpha -}}
+{{ $template }}
+{{ end -}}
+EOF
+    # '{{ includeTemplate "pluck.tmpl" (dict "key" "before_script" "values" .packages.'"$key"') | trim }}'
+    # '{{ includeTemplate "pluck.tmpl" (dict "key" "after_script" "values" .packages.'"$key"') | trim }}'
     return 0
     ;;
   json) format="toPrettyJson" ;;
@@ -99,9 +112,9 @@ diff_packages() {
   current="${installed_packages}.${key:-txt}"
   if [ "$key" = uv ]; then
     # pg_activity[psycopg] -> pg-activity
-    chezmoi package list --type="$key" | cut -d[ -f1 | sed -e 's/_/-/' | sort >"$expected"
+    chezmoi package list "$key" | cut -d[ -f1 | sed -e 's/_/-/' | sort >"$expected"
   else
-    chezmoi package list --type="$key" | sort >"$expected"
+    chezmoi package list "$key" | sort >"$expected"
   fi
   list-package "$key" | sort >"$current"
   # echo >&2 "Diffing $key packages..."
@@ -110,12 +123,7 @@ diff_packages() {
 
 main() {
   command="$1"
-  if [ -n "$type" ] && [ "$type" != all ]; then
-    manager="$type"
-  else
-    manager="$(package-manager)"
-  fi
-  "${command}_packages" "$manager"
+  "${command}_packages" "$(package-manager "$type")"
   if [ "$type" != all ]; then
     exit 0
   fi
@@ -123,10 +131,11 @@ main() {
     "${command}_packages" aur
   fi
   if command -v brew >/dev/null; then
-    "${command}_packages" brew
     if [ "$uname" = Darwin ]; then
       "${command}_packages" cask
       "${command}_packages" mas
+    else
+      "${command}_packages" brew
     fi
     # "${command}_packages" vscode
   fi
