fix: container [ci skip]

diff --git a/script/container b/script/container
--- a/script/container
+++ b/script/container
@@ -6,10 +6,12 @@ set -euo pipefail
 
 # EPHEMERAL="${EPHEMERAL:-false}"
 # HEADLESS="${HEADLESS:-false}"
-# PROFILE="${PROFILE:-minimal}"
+PROFILE="${PROFILE:-minimal}"
 
-PROVIDER="${PROVIDER:-podman}"
-PREFIX="${PREFIX:-}" # Termux prefix
+# WARN: podman does not support dockerfile_inline via docker compose
+# Podman Engine 5.6.1 + Docker Compose version 2.39.4
+PROVIDER="${PROVIDER:-docker}"
+PREFIX="${PREFIX:-}" # termux prefix
 prefix=              # /opt or HOME
 
 usage() {
@@ -20,64 +22,128 @@ usage() {
   echo >&2 "  container alpine up --build --detach"
   echo >&2 "  container alpine logs --follow --since=1m"
   # echo >&2 "  container alpine attach --no-stdin"
-  echo >&2 "  container alpine [check|test]"
+  echo >&2 "  container alpine [check|test|exec|run]"
   echo >&2
-  echo >&2 "Images: alpine, archlinux, debian, ubuntu, fedora"
+  echo >&2 "Images: alpine, archlinux, debian, ubuntu, fedora, termux"
 }
 
-compose_file() {
-  local interactive=true
-  # local sh_args=eux
-  # if [ "$interactive" = true ]; then
-  #   sh_args="i$sh_args"
+container() {
+  local build
+  if [ -z "$prefix" ]; then
+    # prefix="$HOME/.local/share"
+    prefix="/opt" # "$HOME/.local/state"
+  fi
+  local user=test # root
+  # Environment must contain at least one element be a mapping
+  local environment=()
+  # NOTE: container is recreated when command changes
+  local command=()
+  local volumes=()
+  # if [ -z "$tag" ]; then
+  #   image="$name:latest"
+  #   tag=latest
   # fi
-  cat <<EOF
----
-services:
-  $name:
-    # container_name: "${name}-${tag}"
-    image: "$image"
-    environment:
-$(for e in "${environment[@]}"; do echo "      - $e"; done)
-    # entrypoint: ["/bin/sh", "-ceiux"]
-    command:
-      - sh
-      - -ceiux
-      - |
-$(for c in "${command[@]}"; do echo "        $c"; done)
-    volumes:
-$(for v in "${volumes[@]}"; do echo "      - $v"; done)
-    stdin_open: $interactive
-    tty: $interactive
-    user: $container_user
-    working_dir: $working_dir
-EOF
+  if [ -n "${GITHUB_TOKEN:-}" ]; then
+    env+=("GITHUB_TOKEN=$GITHUB_TOKEN")
+  fi
+  case "${image%:*}" in
+  alpine)
+    environment+=(
+      # "LANG=C"
+    )
+    build="apk update --quiet && apk add bash curl sudo unzip"
+    compose "$@"
+    ;;
+  android | termux)
+    export user=a0_test
+    # docker run -it --rm termux/termux-docker:latest bash -c "apt update && apt search example"
+    image=docker.io/termux/termux-docker:x86_64
+    # environment+=()
+    # TODO: pre-select mirrors with termux-change-repo
+    command+=()
+    # PREFIX=/data/data/com.termux/files/usr
+    prefix=/data/data/com.termux/files/home # /.local/state
+    compose "$@"
+    ;;
+  archlinux)
+    environment+=(
+      # "LANG=C"
+    )
+    # pacman -Sy --needed --noconfirm --quiet sudo which
+    build="pacman --sync --needed --noconfirm --quiet --refresh sudo which"
+    # user=$user
+    # pacman --sync --needed --noconfirm --quiet --refresh sudo which
+    # useradd -ms /bin/bash "$user"
+    # usermod -aG wheel "$user"
+    # sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
+    # echo -n "$user:$user" | chpasswd -e "$user"
+    compose "$@"
+    ;;
+  debian | ubuntu)
+    if [ "$image" = ubuntu ]; then
+      export user=ubuntu
+      environment+=(
+        "TZ=${TZ:-Etc/UTC}"
+      )
+    fi
+    environment+=(
+      "DEBIAN_FRONTEND=noninteractive"
+      # "LANG=C"
+    )
+    build="apt-get update --quiet && apt-get install --no-install-recommends --quiet --yes ca-certificates curl locales sudo unzip" #  && rm -rf /var/lib/apt/lists/*
+    compose "$@"
+    ;;
+  fedora)
+    environment+=(
+      # "LANG=C"
+    )
+    build="dnf update --assumeyes --quiet && dnf install -y -q which unzip" # && dnf clean all
+    compose "$@"
+    ;;
+
+  # freebsd)
+  #   image=docker.io/freebsd/freebsd-runtime:15.0.beta2
+  #   compose "$@"
+  #   ;;
+
+  # macOS
+  # https://github.com/sickcodes/Docker-OSX#building-a-headless-osx-container
+  # https://github.com/sickcodes/Docker-OSX/issues/492
+  macos)
+    # Arch: sudo pacman -S xorg-xhost && xhost +
+    # Windows: /mnt/wslg/.X11-unix:/tmp/.X11-unix
+    image=docker.io/sickcodes/docker-osx:auto # ${tag:-auto}
+    environment+=(
+      # "GENERATE_UNIQUE=true"
+      # "MASTER_PLIST_URL="
+      # "NONINTERACTIVE=1"
+      # "OSX_COMMANDS='echo OK; ioreg -l | grep IOPlatformSerialNumber'"
+    )
+    volumes+=("/tmp/.X11-unix:/tmp/.X11-unix")
+    compose "--publish=50922:10022" "$@"
+    ;;
+  *)
+    echo >&2 "container: invalid image: $image"
+    usage
+    exit 1
+    ;;
+  esac
 }
 
 compose() {
   local home=/root
-  local container_user=root
-  # if [ "$user" = test ]; then
-  #   container_user=root
-  # fi
   if [ "$user" != root ]; then
-    home="/home/$user"
+    home="${prefix:-/home}/$user"
   fi
   local working_dir="$home/.local/share/chezmoi"
   local bootstrap="./script/container bootstrap"
-  # if [ "$user" != root ] && [ "$user" != ubuntu ]; then
-  #   command+=(
-  #     "if ! id $user; then useradd -ms /bin/bash $user; fi"
-  #     "usermod -aG wheel $user"
-  #     "sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers"
-  #     # FIXME: not compatible with mounted volume
-  #     # "chown -R $user:$user $home"
-  #     # "su $user"
-  #   )
-  #   bootstrap="su - $user -c 'ls -lah .local/share; cd \"$working_dir\"; ls -lah $bootstrap'"
-  # fi
+  environment+=(
+    # "CONTAINER_NAME=$name"
+    # "CONTAINER_USER=$user"
+    "USER=$user"
+  )
   command+=(
-    "[ -f $prefix/install.done ] || touch $prefix/install.done"
+    # "[ -f $prefix/install.done ] || touch $prefix/install.done"
     "$bootstrap"
   )
   volumes+=(
@@ -93,6 +159,14 @@ compose() {
     elif [ "$1" = test ]; then
       set -- exec -T "$name" ./script/test --pretty
     fi
+  elif [ $# -gt 1 ] && [ "$1" = exec ]; then
+    shift
+    set -- exec -T "$name" "$@"
+  # elif [ $# -gt 1 ] && [ "$1" = run ]; then
+  #   shift
+  #   # You have to remove (or rename) that container to be able to reuse that name
+  #   local dir=chezmoi n=1
+  #   set -- run --name="$dir-$name-$n" -T "$name" "$@"
   fi
   echo >&2 "$PROVIDER compose --file=- $*"
   compose_file="$(compose_file)"
@@ -109,9 +183,79 @@ $compose_file
 EOF
 }
 
-bootstrap() {
-  if [ $# -ne 0 ]; then
-    echo >&2 "WARN: ignoring bootstrap args: $*"
+compose_file() {
+  local interactive=true
+  # local sh_args=eux
+  # if [ "$interactive" = true ]; then
+  #   sh_args="i$sh_args"
+  # fi
+  cat <<EOF
+---
+networks:
+  test:
+services:
+  $name:
+    # container_name: "${name}-${tag}"
+    # image: "$image"
+    build:
+      context: .
+$(if [ "$user" = ubuntu ]; then echo "      # network: host"; fi)
+      # no_cache: true
+      dockerfile_inline: |
+        FROM $image
+
+$(if [ -n "$build" ]; then echo "        RUN $build"; fi)
+$(if [ "$user" = test ]; then
+    echo "        USER $user"
+    echo "        ENV HOME /home/$user"
+  fi)
+    environment:
+$(for e in "${environment[@]}"; do echo "      - $e"; done)
+    # entrypoint: ["/bin/sh", "-ceiux"]
+    command:
+      - sh
+      - -ceiux
+      - |
+$(for c in "${command[@]}"; do echo "        $c"; done)
+    volumes:
+$(for v in "${volumes[@]}"; do echo "      - $v"; done)
+    networks:
+      - test
+    stdin_open: $interactive
+    tty: $interactive
+    user: "$(if [[ "$user" = *test ]]; then echo root; else echo "$user"; fi)"
+    working_dir: "$working_dir"
+EOF
+}
+
+# Runs in container
+run_bootstrap() {
+  local bootstrap=(./script/bootstrap --force --no-tty)
+  # local user="${1:-$USER}"
+  if [ -z "${USER:-}" ]; then
+    USER="$(id --user --name)"
+  fi
+  if [ "$USER" != root ] && [ "$HOME" = /root ]; then
+    HOME="/home/$USER"
+    # echo >&2 "Invalid $USER home: $HOME"
+    # exit 1
+  fi
+
+  if [ "$USER" = test ]; then
+    if ! id --user "$USER" >/dev/null 2>&1; then
+      echo >&2 "Creating user: $USER"
+      if command -v useradd >/dev/null; then
+        # useradd -ms /bin/bash "$USER"
+        useradd --create-home --shell=/bin/bash "$USER"
+        # if groups | grep -qv wheel; then
+        #   groupadd wheel
+        # fi
+        usermod -aG wheel "$USER"
+        sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
+      else
+        adduser -Ds /bin/bash "$USER" # -G wheel
+      fi
+    fi
   fi
 
   # Ensure chezmoi is available
@@ -122,7 +266,7 @@ bootstrap() {
   # 2764 Segmentation fault (core dumped) bash -i
   export BLE_ENABLED=false
 
-  # export CHEZMOI_PROFILE=$PROFILE
+  export CHEZMOI_PROFILE=$PROFILE
   export CI=true
 
   if [ "${DEBUG:-}" = true ]; then
@@ -133,9 +277,17 @@ bootstrap() {
     set -- --verbose "$@"
   fi
 
-  local bootstrap=("./script/bootstrap")
+  set -x
+
+  # mkdir -p "$HOME/.config/"{atuin,bash,bat,blesh,carapace/specs,curl,eza,mise,nushell/{functions,modules,themes},procs,readline,ripgrep,sh/{functions,plugins},starship,wget,yamllint,zsh}
+  # mkdir -p "$HOME/"{.brew-aliases,.config/{homebrew,psql},.local/share,.ssh/config.d}
+
+  # if [ "$USER" = test ]; then
+  #   # su "$USER" -c "pwd; ls -la; echo ${bootstrap[*]} $*"
+  #   sudo -E "${bootstrap[@]}" "$@"
+  # fi
   if [ -n "$PREFIX" ]; then
-    # Install chezmoi with package manager to avoid error on tag:
+    # Install chezmoi with termux package manager to avoid error on tag:
     # latest: critical %s: unsupported platform\n android/386
     # x86_64: android/amd64
     # i686: android/386
@@ -143,144 +295,25 @@ bootstrap() {
     command -v chezmoi >/dev/null || pkg install --quiet --yes chezmoi
     # "tls: failed to verify certificate: x509: certificate signed by unknown authority"
     command -v proot >/dev/null || pkg install --quiet --yes proot
-    bootstrap=(
-      proot -b "$PREFIX/etc/resolv.conf:/etc/resolv.conf" -b "$PREFIX/etc/tls:/etc/ssl"
-      "${bootstrap[@]}"
-    )
+    proot \
+      -b "$PREFIX/etc/resolv.conf:/etc/resolv.conf" \
+      -b "$PREFIX/etc/tls:/etc/ssl" \
+      "${bootstrap[@]}" "$@"
+  else
+    "${bootstrap[@]}" "$@"
   fi
 
-  set -x
+  ./script/check
 
-  # mkdir -p "$HOME/.config/"{atuin,bash,bat,blesh,carapace/specs,curl,eza,mise,nushell/{functions,modules,themes},procs,readline,ripgrep,sh/{functions,plugins},starship,wget,yamllint,zsh}
-  "${bootstrap[@]}" --force --no-tty "$@"
-
-  # ./script/check
-  # ./script/test --pretty # --filter-tags '!bench,!check,!chezmoi'
+  if [ -d /home/linuxbrew/.linuxbrew/bin ]; then
+    PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
+  fi
+  ./script/test --pretty # --filter-tags '!bench,!check,!chezmoi'
 
   # Keep the container running
-  bash -i
+  # bash -i
   # bash -l
   # watch -n60 chezmoi status
-}
-
-container() {
-  if [ -z "$prefix" ]; then
-    # prefix="$HOME/.local/share"
-    prefix="/opt" # "$HOME/.local/state"
-  fi
-  local user=root
-  # Environment must contain at least one element be a mapping
-  local environment=("CONTAINER_NAME=$name")
-  # NOTE: container is recreated when command changes
-  local command=()
-  local volumes=()
-  # if [ -z "$tag" ]; then
-  #   image="$name:latest"
-  #   tag=latest
-  # fi
-  if [ -n "${GITHUB_TOKEN:-}" ]; then
-    env+=("GITHUB_TOKEN=$GITHUB_TOKEN")
-  fi
-  case "$name" in
-  alpine)
-    environment+=(
-      "LANG=C"
-      # "USER=$user"
-    )
-    command+=(
-      "[ -f $prefix/install.done ] || apk update --quiet"
-      "[ -f $prefix/install.done ] || apk add bash curl" # sudo unzip
-    )
-    compose "$@"
-    ;;
-  archlinux)
-    user="test"
-    environment+=(
-      "LANG=C"
-      # "USER=$user"
-    )
-    command+=(
-      # "pacman -Sy --needed --noconfirm --quiet sudo which"
-      "[ -f $prefix/install.done ] || pacman --sync --needed --noconfirm --quiet --refresh sudo which"
-
-      # user=$user
-      # pacman --sync --needed --noconfirm --quiet --refresh sudo which
-      # useradd -ms /bin/bash "$user"
-      # usermod -aG wheel "$user"
-      # sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
-      # echo -n "$user:$user" | chpasswd -e "$user"
-    )
-    compose "$@"
-    ;;
-  debian | ubuntu)
-    if [ "$image" = ubuntu ]; then
-      user=ubuntu
-    fi
-    environment+=(
-      "DEBIAN_FRONTEND=noninteractive"
-      "LANG=C"
-      "TZ=${TZ:-Etc/UTC}" # ubuntu
-      # "USER=$user"
-    )
-    command+=(
-      "[ -f $prefix/install.done ] || apt-get update --quiet"
-      "[ -f $prefix/install.done ] || apt-get install --no-install-recommends --quiet --yes ca-certificates curl locales" # sudo unzip
-      # "rm -rf /var/lib/apt/lists/*"
-    )
-    compose "$@"
-    ;;
-  fedora)
-    environment+=(
-      "DEBIAN_FRONTEND=noninteractive"
-      "LANG=C"
-      # "USER=$user"
-    )
-    command+=(
-      "[ -f $prefix/install.done ] || dnf update --assumeyes --quiet"
-      "[ -f $prefix/install.done ] || dnf install -y -q which unzip"
-      # "dnf clean all"
-    )
-    compose "$@"
-    ;;
-
-  # macOS
-  # https://github.com/sickcodes/Docker-OSX#building-a-headless-osx-container
-  # https://github.com/sickcodes/Docker-OSX/issues/492
-  macos)
-    # Arch: sudo pacman -S xorg-xhost && xhost +
-    # Windows: /mnt/wslg/.X11-unix:/tmp/.X11-unix
-    image=docker.io/sickcodes/docker-osx:auto # ${tag:-auto}
-    environment+=(
-      # "GENERATE_UNIQUE=true"
-      # "MASTER_PLIST_URL="
-      # "NONINTERACTIVE=1"
-      # "OSX_COMMANDS='echo OK; ioreg -l | grep IOPlatformSerialNumber'"
-    )
-    # command+=()
-    volumes+=("/tmp/.X11-unix:/tmp/.X11-unix")
-    compose "--publish=50922:10022" "$@"
-    ;;
-
-  # docker run -it --rm termux/termux-docker:latest bash -c "apt update && apt install -yq clang"
-  android | termux)
-    user=a0_test
-    image=docker.io/termux/termux-docker:x86_64
-    environment+=(
-      # "USER=$user"
-    )
-    # TODO: pre-select mirrors with termux-change-repo
-    command+=()
-    # PREFIX=/data/data/com.termux/files/usr
-    prefix=/data/data/com.termux/files/home # /.local/state
-    compose "$@"
-    ;;
-
-  *)
-    echo >&2 "container: invalid image: $image"
-    usage
-    exit 1
-    ;;
-  esac
 }
 
 main() {
@@ -288,14 +321,21 @@ main() {
     usage
     exit
   fi
-  local image="$1"
+  local arg="$1"
   shift
-  local name="${image%%:*}" tag="${image#*:}"
-  if [ "$name" = bootstrap ]; then
-    bootstrap "$@"
-  else
-    container "$@"
+  if [ "$arg" = bootstrap ]; then
+    run_bootstrap "$@"
+    return
   fi
+  local image="$arg" tag=latest
+  if [[ "$image" = *:* ]]; then
+    tag="${image#*:}"
+    name="${image%%:*}-$tag"
+  else
+    name="$image-$tag"
+    image="$image:$tag"
+  fi
+  container "$@"
 }
 
 main "$@"
