script

diff --git a/script/dotfiles b/script/dotfiles
--- a/script/dotfiles
+++ b/script/dotfiles
@@ -38,7 +38,7 @@ boot() {
   import "lib/prompt"
   import "lib/config"
 
-  # Parse command options
+  # Parse command options, main command empty by default
   DOT_CMD=
   parse_arguments "$@"
 
@@ -72,87 +72,18 @@ boot() {
   dot "$DOT_CMD"
 }
 
-dot() {
-  local cmd=$1
+check_env() {
+  MIN_BASH_VERSION=3
+  ENV_BASH_VERSION=${BASH_VERSION%%[^0-9]*}
 
-  case $cmd in
-    install)
-      dot_install
-      ;;
-    git)
-      dot_git
-      ;;
-    list)
-      dot_list
-      ;;
-    link)
-      dot_bootstrap
-      ;;
-    defaults)
-      dot_defaults
-      ;;
-    '') # Default to all
-      if confirm "Update repository" "" Y; then
-        dot_git
-      fi
-      if confirm "**Install packages" "" Y; then
-        dot_install
-      fi
-      if confirm "**Symlink files to $DOT_TARGET" "" Y; then
-        dot_bootstrap
-      fi
-      if confirm "**Setup $UNAME defaults" "" Y; then
-        dot_defaults
-      fi
-      ;;
-    *)
-      log_error "Unsupported command" "$cmd"
-      die "$cmd"
-      ;;
-  esac
-
-  if [[ $? -eq 0 ]]; then
-    log_success "Done" "= $?"
-  else
-    log_error "Error" "= $?"
-    return $?
+  if [[ $ENV_BASH_VERSION -lt $MIN_BASH_VERSION ]]; then
+    die "This script requires bash > ${MIN_BASH_VERSION}"
   fi
-}
 
-dot_install() {
-  import "install"
-
-  # Install dependencies
-  install_packages || \
-    log_warn "Install aborted" "= $?"
-}
-
-dot_git() {
-  import "lib/git"
-  git_submodule_update
-}
-
-dot_bootstrap() {
-  import "bootstrap/templates"
-  import "bootstrap/symlinks"
-
-  # Bootstrap dotfiles
-  bootstrap_templates && \
-    bootstrap_symlinks build || \
-    log_warn "Bootstrap aborted" "= $?"
-}
-
-dot_list() {
-  import "bootstrap/symlinks"
-  bootstrap_symlinks list
-}
-
-dot_defaults() {
-  import "defaults"
-
-  # Set platform defaults
-  os_defaults || \
-    log_warn "Defaults aborted" "= $?"
+  # Check files?
+  if [[ ! -d "${DOT_ROOT-}" ]]; then
+    die "${DOT_ROOT-undefined}: '\$DOT_ROOT' is not a directory"
+  fi
 }
 
 parse_arguments() {
@@ -162,11 +93,17 @@ parse_arguments() {
     # echo "Parsing $1 (#$#)"
     case $key in
       # All dot commands
-      git|list|install|uninstall|link|unlink|defaults)
+      install|uninstall|update|list|link|unlink|defaults)
         # Check if a command is already registered
         [[ -n "${DOT_CMD-}" ]] && usage 1 "Too many arguments: $key"
-        # Register main action
-        DOT_CMD="$key"
+        key="dot_$key"
+        if is_function $key; then
+          # Register main action
+          DOT_CMD="$key"
+        else
+          log_error "Unsupported command" "$key"
+          die "$key"
+        fi
         shift
         ;;
       -v|--verbose|--debug)
@@ -214,24 +151,77 @@ parse_arguments() {
   done
 }
 
-check_env() {
-  MIN_BASH_VERSION=3
-  ENV_BASH_VERSION=${BASH_VERSION%%[^0-9]*}
+dot() {
+  local cmd=$1
 
-	if [[ $ENV_BASH_VERSION -lt $MIN_BASH_VERSION ]]; then
-		die "This script requires bash > ${MIN_BASH_VERSION}"
-	fi
+  case $cmd in
+    '') # Default process
+      if confirm "**Update repository" "" Y; then
+        dot_update
+      fi
+      if confirm "**Install packages" "" Y; then
+        dot_install
+      fi
+      if confirm "**Symlink files to $DOT_TARGET" "" Y; then
+        dot_bootstrap
+      fi
+      if confirm "**Setup $UNAME defaults" "" Y; then
+        dot_defaults
+      fi
+      ;;
+    *) # Execute function
+      $cmd
+      ;;
+  esac
 
-  # Check files?
-  if [[ ! -d "${DOT_ROOT-}" ]]; then
-    die "${DOT_ROOT-undefined}: '\$DOT_ROOT' is not a directory"
+  if [[ $? -eq 0 ]]; then
+    log_success "Done" "= $?"
+  else
+    log_error "Error" "= $?"
+    return $?
   fi
 }
 
-die() {
-  local message=${1:-Died}
-  printf "%s\r\n" "${BASH_SOURCE[1]}: line ${BASH_LINENO[0]}: ${FUNCNAME[1]}: $message" >&2
-  exit 1
+dot_install() {
+  import "install"
+
+  # Install dependencies
+  install_packages || \
+    log_warn "Install aborted" "= $?"
+}
+
+#dot_uninstall()
+
+dot_update() {
+  import "lib/git"
+
+  # Pulls
+  git_submodule_update
+}
+
+dot_list() {
+  import "bootstrap/symlinks"
+  bootstrap_symlinks list
+}
+
+dot_link() {
+  import "bootstrap/templates"
+  import "bootstrap/symlinks"
+
+  # Bootstrap dotfiles
+  bootstrap_templates && \
+    bootstrap_symlinks build || \
+    log_warn "Bootstrap aborted" "= $?"
+}
+
+#dot_unlink()
+
+dot_defaults() {
+  import "defaults"
+
+  # Set platform defaults
+  os_defaults || \
+    log_warn "Defaults aborted" "= $?"
 }
 
 [[ "$0" == "$BASH_SOURCE" ]] && boot "$@"
