fix: misc [ci skip]

diff --git a/script/entrypoint b/script/entrypoint
--- a/script/entrypoint
+++ b/script/entrypoint
@@ -1,19 +1,35 @@
 #!/bin/sh
 
-# Create a non-root user 'test' with sudo privileges
+# Install bootstrap dependencies and create a test user with sudo privileges
 
 set -eux
 
+if [ $# -ne 0 ]; then
+  echo >&2 "Invalid arguments: $*"
+  exit 2
+fi
+
+entrypoint() {
+  set -- tail -f /dev/null
+  if [ -f /entrypoint.sh ]; then
+    /entrypoint.sh "$@"
+  else
+    exec "$@"
+  fi
+}
+
 if [ -n "${PREFIX:-}" ]; then
-  echo >&2 "Skip in termux"
+  echo >&2 "Skipping in termux"
+  entrypoint
   exit
 fi
 
-# if [ -z "${USER:-}" ]; then
-#   USER="$(id --user --name)"
-# fi
+test_user="${TEST_USER:-test}"
 
-test_user="$1"
+admin_group=wheel
+# if getent group sudo >/dev/null; then
+#   admin_group=sudo
+# fi
 
 if [ -z "$test_user" ]; then
   echo >&2 "Missing user name"
@@ -28,6 +44,27 @@ test) ;;
   exit 1
   ;;
 esac
+
+install_packages() {
+  if command -v apk >/dev/null; then
+    apk update --quiet
+    apk add bash chezmoi curl sudo unzip
+  elif command -v apt-get >/dev/null; then
+    apt-get update --quiet
+    apt-get install --no-install-recommends --quiet --yes ca-certificates curl locales sudo unzip
+  elif command -v dnf >/dev/null; then
+    dnf update --assumeyes --quiet
+    dnf install --assumeyes --quiet chezmoi which unzip
+  elif command -v pacman >/dev/null; then
+    # if [ -n "${CI:-}" ] && [ "$(uname -m)" = "aarch64" ]; then
+    #   pacman-key --init # pacman-key --populate archlinux
+    # fi
+    pacman --sync --needed --noconfirm --quiet --refresh chezmoi sudo which
+  else
+    echo >&2 "bootstrap-deps: unsupported package manager"
+    exit 1
+  fi
+}
 
 create_user() {
   user="$1"
@@ -66,11 +103,7 @@ create_group() {
   fi
 }
 
-admin_group=wheel
-# if getent group sudo >/dev/null; then
-#   admin_group=sudo
-# fi
-
+install_packages
 create_user "$test_user"
 create_group "$test_user" "$test_user"
 create_group "$test_user" "$admin_group"
@@ -81,11 +114,8 @@ if [ -f /etc/sudoers ]; then
     sed \
       -e "s/^# %$admin_group ALL=(ALL:ALL) NOPASSWD: ALL/%$admin_group ALL=(ALL:ALL) NOPASSWD: ALL/" \
       -i /etc/sudoers
-  elif ! grep -q "^%$admin_group ALL=(ALL:ALL) NOPASSWD: ALL" /etc/sudoers; then
-    if [ -f "/etc/sudoers.d/$admin_group" ]; then
-      echo >&2 "Sudoers file /etc/sudoers.d/$admin_group already exists, aborting"
-      exit 1
-    fi
+  elif ! grep -q "^%$admin_group ALL=(ALL:ALL) NOPASSWD: ALL" /etc/sudoers &&
+    ! [ -f "/etc/sudoers.d/$admin_group" ]; then
     echo "%$admin_group ALL=(ALL:ALL) NOPASSWD: ALL" >"/etc/sudoers.d/$admin_group"
   fi
 fi
@@ -102,3 +132,5 @@ if ! groups "$test_user" | grep -q "$admin_group"; then
   echo >&2 "User '$test_user' is not in $admin_group group, aborting"
   exit 1
 fi
+
+entrypoint
