fix: packages [ci skip]

diff --git a/script/vm b/script/vm
--- a/script/vm
+++ b/script/vm
@@ -12,14 +12,14 @@
 
 set -euo pipefail
 
-script_dir="${BASH_SOURCE[0]%/*}"
-# shellcheck source=home/dot_local/lib/bash/log.sh
-source "$script_dir/../home/dot_local/lib/bash/log.sh"
+lib_dir="${BASH_SOURCE[0]%/*}/../home/dot_local/lib"
+# shellcheck source=home/dot_local/lib/sh/log.sh
+source "$lib_dir/sh/log.sh"
 # shellcheck source=home/dot_local/lib/bash/require.sh
-source "$script_dir/../home/dot_local/lib/bash/require.sh"
+source "$lib_dir/bash/require.sh"
 
 require_bash 4
-err_trap
+trap 'log "error at line $LINENO"' ERR
 
 if [ -z "${VM_PROVIDER:-}" ]; then
   case "$(uname -s)" in
